#ifndef __ERRORS_H__
#define __ERRORS_H__

#include <stdlib.h>
#include <stdio.h>

void print_add_err(int rc);

#define COUNTRY_DIGIT_ERR 2
#define CAPITAL_DIGIT_ERR 3
#define MATERIC_DIGIT_ERR 4
#define COUNTRY_OVERFLOW 5
#define CAPITAL_OVERFLOW 6
#define MATERIC_OVERFLOW 7
#define INCORRECT_COUNTRY_SYMB 8
#define INCORRECT_CAPITAL_SYMB 9
#define NOT_IS_MATERIC 10
#define POPULATION_ZERO_ERROR 11
#define NOT_DIGIT_POPULATION 12
#define TESTS_VALUE_ERR 13
#define DATA_EMPTY_ERR 14
#define INCORRECT_STR 15
#define BASE_PARAMS_ERROR 16
#define VAR_STRING_OVERFLOW 17

#define NOT_DIGIT_NUMBER_OBJECTS 19
#define NUMBER_OBJECTS_IS_NEGATIVE 20
#define NAME_OBJECT_OVERFLOW 21
#define SIGHT_PARAM_ERROR 22

#define NOT_DIGIT_MAIN_SEASON 23
#define MAIN_SEASON_IS_NEGATIVE 24
#define NOT_DIGIT_AIR_TEMP 25
#define NOT_DIGIT_WATER_TEMP 26
#define WATER_TEMP_IS_NEG 27
#define NOT_DIGIT_TIME_FLYING 28
#define TIME_FLYING_IS_NEG 29
#define BEACH_PARAM_ERROR 30
#define ERROR_NAME_OBJECT 39

#define STRING_SPORT_OVERFLOW 31
#define NOT_DIGIT_MIN_COUNT_PRICE 32
#define MIN_COUNT_PRICE_IS_NEG 33
#define SPORT_PARAM_ERROR 34
#define ERROR_TYPE_SPORT 40

#define SCAN_ERROR 35
#define STRING_OVERFLOW 36
#define MAIN_PARAM_ERROR 37
#define FILE_NOT_FOUND 38

#define NOT_FIND 41
#define NOT_TEST 42
#define MAIN_SEASON_ERROR 43
#define STRUCT_OVERFLOW 44
#define SAME_NAME 45
#define SPORT_DIGIT_ERROR 46

#endif
